using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using TwinCAT.Ads;
using PLCManager.Demo.Enum;
using PLCManager.Demo.Struct;
using PLCManager.Demo.Wrapper;
using PlcCore.Beckhoff;
using PlcCore.Data;

namespace PLCManager.Demo.Root
{
	
	internal static class GetClass_a3f9b53901d7438ca4883cf4a50dd6dd
	{
		internal static ref bool GetFrame_transfer_motion(this GVL_SetupWrapper parent) => ref parent.ref_Frame_transfer_motion;
		internal static ref float GetIMH_Loading_Y_Origin(this GVL_SetupWrapper parent) => ref parent.ref_IMH_Loading_Y_Origin;
		internal static ref float GetIMH_Loading_Z_Origin(this GVL_SetupWrapper parent) => ref parent.ref_IMH_Loading_Z_Origin;
		internal static ref float GetIMH_Loading_Z_Limit(this GVL_SetupWrapper parent) => ref parent.ref_IMH_Loading_Z_Limit;
		internal static ref float GetIMH_Loading_Table_Height(this GVL_SetupWrapper parent) => ref parent.ref_IMH_Loading_Table_Height;
		internal static ref float GetIMH_Loading_Height_Before(this GVL_SetupWrapper parent) => ref parent.ref_IMH_Loading_Height_Before;
		internal static ref float GetIMH_Loading_Height_After(this GVL_SetupWrapper parent) => ref parent.ref_IMH_Loading_Height_After;
		internal static ref float GetIMH_UnLoading_Position(this GVL_SetupWrapper parent) => ref parent.ref_IMH_UnLoading_Position;
		internal static ref float GetIMH_UnLoad_Table_Height(this GVL_SetupWrapper parent) => ref parent.ref_IMH_UnLoad_Table_Height;
		internal static ref float GetIMH_UnLoading_Height_Before(this GVL_SetupWrapper parent) => ref parent.ref_IMH_UnLoading_Height_Before;
		internal static ref float GetIMH_UnLoading_Height_After(this GVL_SetupWrapper parent) => ref parent.ref_IMH_UnLoading_Height_After;
		internal static ref float GetOMH_UnLoading_Y_Origin(this GVL_SetupWrapper parent) => ref parent.ref_OMH_UnLoading_Y_Origin;
		internal static ref float GetOMH_UnLoading_Z_Origin(this GVL_SetupWrapper parent) => ref parent.ref_OMH_UnLoading_Z_Origin;
		internal static ref float GetOMH_UnLoading_Z_Limit(this GVL_SetupWrapper parent) => ref parent.ref_OMH_UnLoading_Z_Limit;
		internal static ref float GetOMH_Loading_Table_Height(this GVL_SetupWrapper parent) => ref parent.ref_OMH_Loading_Table_Height;
		internal static ref float GetOMH_Loading_Height_Before(this GVL_SetupWrapper parent) => ref parent.ref_OMH_Loading_Height_Before;
		internal static ref float GetOMH_Loading_Height_After(this GVL_SetupWrapper parent) => ref parent.ref_OMH_Loading_Height_After;
		internal static ref float GetOMH_UnLoading_Position(this GVL_SetupWrapper parent) => ref parent.ref_OMH_UnLoading_Position;
		internal static ref float GetOMH_UnLoading_Table_Height(this GVL_SetupWrapper parent) => ref parent.ref_OMH_UnLoading_Table_Height;
		internal static ref float GetOMH_UnLoading_Height_Before(this GVL_SetupWrapper parent) => ref parent.ref_OMH_UnLoading_Height_Before;
		internal static ref float GetOMH_UnLoading_Height_After(this GVL_SetupWrapper parent) => ref parent.ref_OMH_UnLoading_Height_After;
		internal static ref bool GetWafer_motion(this GVL_SetupWrapper parent) => ref parent.ref_Wafer_motion;
		internal static ref bool GetClean_motion(this GVL_SetupWrapper parent) => ref parent.ref_Clean_motion;
		internal static ref bool GetFrame_transfer_speed(this GVL_SetupWrapper parent) => ref parent.ref_Frame_transfer_speed;
		internal static ref bool GetClean_speed(this GVL_SetupWrapper parent) => ref parent.ref_Clean_speed;
		internal static ref bool GetPreform_Speed(this GVL_SetupWrapper parent) => ref parent.ref_Preform_Speed;
		internal static ref bool GetUtility_Check(this GVL_SetupWrapper parent) => ref parent.ref_Utility_Check;
		internal static ref bool GetNo_frame_error_stop(this GVL_SetupWrapper parent) => ref parent.ref_No_frame_error_stop;
		internal static ref bool GetDouble_frame_detection(this GVL_SetupWrapper parent) => ref parent.ref_Double_frame_detection;
		internal static ref bool GetPS_vacuum_detection(this GVL_SetupWrapper parent) => ref parent.ref_PS_vacuum_detection;
		internal static ref bool GetBS_vacuum_detection(this GVL_SetupWrapper parent) => ref parent.ref_BS_vacuum_detection;
		internal static ref bool GetStage_up_down_mechanism(this GVL_SetupWrapper parent) => ref parent.ref_Stage_up_down_mechanism;
		internal static ref bool GetPre_heat(this GVL_SetupWrapper parent) => ref parent.ref_Pre_heat;
		internal static ref bool GetBond_heat(this GVL_SetupWrapper parent) => ref parent.ref_Bond_heat;
		internal static ref bool GetAfter_heat(this GVL_SetupWrapper parent) => ref parent.ref_After_heat;
		internal static ref short GetIMH_UnLoading_Y_Origin(this GVL_SetupWrapper parent) => ref parent.ref_IMH_UnLoading_Y_Origin;
		internal static ref float GetVac_source_sensor_upper_limit(this GVL_SetupWrapper parent) => ref parent.ref_Vac_source_sensor_upper_limit;
		internal static ref float GetVac_source_sensor_lower_limit(this GVL_SetupWrapper parent) => ref parent.ref_Vac_source_sensor_lower_limit;
		internal static ref float GetAir_source_sensor_upper_limit(this GVL_SetupWrapper parent) => ref parent.ref_Air_source_sensor_upper_limit;
		internal static ref float GetAir_source_sensor_lower_limit(this GVL_SetupWrapper parent) => ref parent.ref_Air_source_sensor_lower_limit;
		internal static ref float GetB_force_air_sensor_upper_limit(this GVL_SetupWrapper parent) => ref parent.ref_B_force_air_sensor_upper_limit;
		internal static ref float GetB_force_air_sensor_lower_limit(this GVL_SetupWrapper parent) => ref parent.ref_B_force_air_sensor_lower_limit;
		internal static ref float GetPS_vacuum_sensor_offset(this GVL_SetupWrapper parent) => ref parent.ref_PS_vacuum_sensor_offset;
		internal static ref float GetBS_vacuum_sensor_offset(this GVL_SetupWrapper parent) => ref parent.ref_BS_vacuum_sensor_offset;
		internal static ref float GetFrame_vacuum_sensor_offset(this GVL_SetupWrapper parent) => ref parent.ref_Frame_vacuum_sensor_offset;
		internal static ref float GetVacuum_source_sensor_offset(this GVL_SetupWrapper parent) => ref parent.ref_Vacuum_source_sensor_offset;
		internal static ref float GetAir_source_sensor_offset(this GVL_SetupWrapper parent) => ref parent.ref_Air_source_sensor_offset;
		internal static ref float GetPreform_CDA_Y_Axis_Origin(this GVL_SetupWrapper parent) => ref parent.ref_Preform_CDA_Y_Axis_Origin;
		internal static ref float GetPreform_CDA_Z_Axis_Origin(this GVL_SetupWrapper parent) => ref parent.ref_Preform_CDA_Z_Axis_Origin;
		internal static ref float GetPreform_Touch_Sensor_Sensitivity(this GVL_SetupWrapper parent) => ref parent.ref_Preform_Touch_Sensor_Sensitivity;
		internal static ref float GetPreform_Nozzle_height_Check_Y_Pos(this GVL_SetupWrapper parent) => ref parent.ref_Preform_Nozzle_height_Check_Y_Pos;
		internal static ref float GetP_Claw_Conflict_Pos_Y(this GVL_SetupWrapper parent) => ref parent.ref_P_Claw_Conflict_Pos_Y;
		internal static ref float GetP_Clamp_Conflict_Left_Pos(this GVL_SetupWrapper parent) => ref parent.ref_P_Clamp_Conflict_Left_Pos;
		internal static ref float GetP_Clamp_Conflict_Right_Pos(this GVL_SetupWrapper parent) => ref parent.ref_P_Clamp_Conflict_Right_Pos;
		internal static ref float GetFIG_Loader_Feeder_Origin(this GVL_SetupWrapper parent) => ref parent.ref_FIG_Loader_Feeder_Origin;
		internal static ref float GetFIG_Loader_Feeder_Left_Limit(this GVL_SetupWrapper parent) => ref parent.ref_FIG_Loader_Feeder_Left_Limit;
		internal static ref float GetFIG_Loader_Feeder_Right_Limit(this GVL_SetupWrapper parent) => ref parent.ref_FIG_Loader_Feeder_Right_Limit;
		internal static ref float GetFIG_Clamp_Origin(this GVL_SetupWrapper parent) => ref parent.ref_FIG_Clamp_Origin;
		internal static ref float GetFIG_Preform_POs(this GVL_SetupWrapper parent) => ref parent.ref_FIG_Preform_POs;
		internal static ref float GetFeeder_RVS_Frame_Detect_Pos(this GVL_SetupWrapper parent) => ref parent.ref_Feeder_RVS_Frame_Detect_Pos;
		internal static ref float GetFCU_Main_Feeder1_Origin(this GVL_SetupWrapper parent) => ref parent.ref_FCU_Main_Feeder1_Origin;
		internal static ref float GetFCU_Main_Feeder1_Left_Limit(this GVL_SetupWrapper parent) => ref parent.ref_FCU_Main_Feeder1_Left_Limit;
		internal static ref float GetFCU_Main_Feeder1_Right_Limit(this GVL_SetupWrapper parent) => ref parent.ref_FCU_Main_Feeder1_Right_Limit;
		internal static ref float GetFCU_Main_Feeder_Claw_Width(this GVL_SetupWrapper parent) => ref parent.ref_FCU_Main_Feeder_Claw_Width;
		internal static ref float GetFCU_Clamp_Origin(this GVL_SetupWrapper parent) => ref parent.ref_FCU_Clamp_Origin;
		internal static ref float GetFBU_Main_Feeder2_Origin(this GVL_SetupWrapper parent) => ref parent.ref_FBU_Main_Feeder2_Origin;
		internal static ref float GetFBU_Main_Feeder2_Left_Limit(this GVL_SetupWrapper parent) => ref parent.ref_FBU_Main_Feeder2_Left_Limit;
		internal static ref float GetFBU_Main_Feeder2_Right_Limit(this GVL_SetupWrapper parent) => ref parent.ref_FBU_Main_Feeder2_Right_Limit;
		internal static ref float GetFBU_Main_Feeder2_Claw_Width(this GVL_SetupWrapper parent) => ref parent.ref_FBU_Main_Feeder2_Claw_Width;
		internal static ref float GetFBU_Clamp_Origin(this GVL_SetupWrapper parent) => ref parent.ref_FBU_Clamp_Origin;
		internal static ref float GetFOG_UF_Claw_Open_Close_Origin(this GVL_SetupWrapper parent) => ref parent.ref_FOG_UF_Claw_Open_Close_Origin;
		internal static ref float GetFOG_Unloader_Feeder_Origin(this GVL_SetupWrapper parent) => ref parent.ref_FOG_Unloader_Feeder_Origin;
		internal static ref float GetFOG_Unloader_Feeder_Left_Limit(this GVL_SetupWrapper parent) => ref parent.ref_FOG_Unloader_Feeder_Left_Limit;
		internal static ref float GetFOG_Unloader_Feeder_Right_Limit(this GVL_SetupWrapper parent) => ref parent.ref_FOG_Unloader_Feeder_Right_Limit;
		internal static ref float GetFOG_Unloading_Detect_Pos(this GVL_SetupWrapper parent) => ref parent.ref_FOG_Unloading_Detect_Pos;
		internal static ref float GetTrack_Width_Origin(this GVL_SetupWrapper parent) => ref parent.ref_Track_Width_Origin;
		internal static ref float GetTrack_Width_Close_Limit(this GVL_SetupWrapper parent) => ref parent.ref_Track_Width_Close_Limit;
		internal static ref float GetTrack_Left_Edge_Pos(this GVL_SetupWrapper parent) => ref parent.ref_Track_Left_Edge_Pos;
		internal static ref float GetTrack_Right_Edge_Pos(this GVL_SetupWrapper parent) => ref parent.ref_Track_Right_Edge_Pos;
		internal static ref float GetWAF_Case_Lifter_Origin(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Case_Lifter_Origin;
		internal static ref float GetWAF_Case_Lifter_Wait_Height(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Case_Lifter_Wait_Height;
		internal static ref float GetWAF_Case_Lifter_Heat_Plate_Height(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Case_Lifter_Heat_Plate_Height;
		internal static ref float GetWAF_Case_Lifter_6inch_Heat_Height(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Case_Lifter_6inch_Heat_Height;
		internal static ref float GetWAF_Case_Lifter_8inch_Heat_Height(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Case_Lifter_8inch_Heat_Height;
		internal static ref float GetWAF_Case_Lifter_12inch_Heat_Height(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Case_Lifter_12inch_Heat_Height;
		internal static ref float GetWAF_Extrator_Origin(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Extrator_Origin;
		internal static ref float GetWAF_Pull_Position(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Pull_Position;
		internal static ref float GetWAF_Adjust_Track_Pos(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Adjust_Track_Pos;
		internal static ref float GetWAF_Holder_Set_Release_Pos(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Holder_Set_Release_Pos;
		internal static ref float GetWAF_Putin_Pos(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Putin_Pos;
		internal static ref float GetWAF_Lifter_Wait_Pos(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Lifter_Wait_Pos;
		internal static ref float GetWAF_Push_Pos(this GVL_SetupWrapper parent) => ref parent.ref_WAF_Push_Pos;
	}

}
