using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using TwinCAT.Ads;
using PLCManager.Demo.Enum;
using PLCManager.Demo.Struct;
using PLCManager.Demo.Wrapper;
using PlcCore.Beckhoff;
using PlcCore.Data;

namespace PLCManager.Demo.Root
{
	
	internal static class GetClass_286a6b54d9dd459582fd2875ade56024
	{
		internal static ref bool GetReversed_Frame_Detection_mode(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Reversed_Frame_Detection_mode;
		internal static ref bool GetReversed_Frame_Detection_logic_1(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Reversed_Frame_Detection_logic_1;
		internal static ref bool GetReversed_Frame_Detection_logic_2(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Reversed_Frame_Detection_logic_2;
		internal static ref bool GetReversed_Frame_Detection_logic_3(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Reversed_Frame_Detection_logic_3;
		internal static ref bool GetReversed_Frame_Detection_logic_4(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Reversed_Frame_Detection_logic_4;
		internal static ref bool GetFeed_Cond_Input_media_type(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_Input_media_type;
		internal static ref bool GetFeed_Cond_Frame_map(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_Frame_map;
		internal static ref bool GetFeed_Cond_Preform_stage_vacuum(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_Preform_stage_vacuum;
		internal static ref bool GetFeed_Cond_Bonding_stage_vacuum(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_Bonding_stage_vacuum;
		internal static ref bool GetFeed_Cond_P_gripper_escape(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_P_gripper_escape;
		internal static ref bool GetFeed_Cond_B_gripper_escape(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_B_gripper_escape;
		internal static ref bool GetFeed_Cond_P_frame_grip_during(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_P_frame_grip_during;
		internal static ref bool GetFeed_Cond_B_frame_grip_during(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_B_frame_grip_during;
		internal static ref bool GetFeed_Cond_P_frame_clamp_during(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_P_frame_clamp_during;
		internal static ref bool GetFeed_Cond_B_frame_clamp_during(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_B_frame_clamp_during;
		internal static ref bool GetFeed_Cond_Cure_action(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feed_Cond_Cure_action;
		internal static ref bool GetStage_Re_clamp_at_Vac_Det_retry(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Stage_Re_clamp_at_Vac_Det_retry;
		internal static ref bool GetAction_after_FRM_pullout_error(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Action_after_FRM_pullout_error;
		internal static ref bool GetFrame_pusher_usage(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Frame_pusher_usage;
		internal static ref bool GetFrame_cleaning(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Frame_cleaning;
		internal static ref bool GetFrame_unload_jam_detection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Frame_unload_jam_detection;
		internal static ref bool GetWafer_Barcode_read(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_Barcode_read;
		internal static ref bool GetOrder_of_wafer_load(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Order_of_wafer_load;
		internal static ref bool GetWafer_auto_unload(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_auto_unload;
		internal static ref bool GetReversed_frame_Rec_mode(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Reversed_frame_Rec_mode;
		internal static ref bool GetBonding_step_motion_mode(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_step_motion_mode;
		internal static ref bool GetPaste_hard_skip_count(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Paste_hard_skip_count;
		internal static ref bool GetPre_heat_motion(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Pre_heat_motion;
		internal static ref bool GetBond_heat_motion(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bond_heat_motion;
		internal static ref bool GetAfrer_heat_motion(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Afrer_heat_motion;
		internal static ref bool GetReverse_frame_detection_mode(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Reverse_frame_detection_mode;
		internal static ref bool GetFrame_map_mode(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Frame_map_mode;
		internal static ref bool GetPreform_stage_vacuum(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_stage_vacuum;
		internal static ref bool GetBonding_stage_vacuum(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_stage_vacuum;
		internal static ref bool GetFeeder_escape_at_preform(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feeder_escape_at_preform;
		internal static ref bool GetFeeder_escape_at_bonding(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Feeder_escape_at_bonding;
		internal static ref bool GetPreform_stage_up_down(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_stage_up_down;
		internal static ref bool GetBonding_stage_up_down(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_stage_up_down;
		internal static ref bool GetFrame_unload_rehold_distance(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Frame_unload_rehold_distance;
		internal static ref bool GetFrame_unload_retry_mode(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Frame_unload_retry_mode;
		internal static ref bool GetWafer_map(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_map;
		internal static ref bool GetWafer_recovery(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_recovery;
		internal static ref bool GetStop_after_last_wafer(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Stop_after_last_wafer;
		internal static ref bool GetWafer_die_position_recognition_Conflict(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_die_position_recognition_Conflict;
		internal static ref bool GetWafer_edge_recognition(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_edge_recognition;
		internal static ref bool GetWafer_ink_mark_recognition(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_ink_mark_recognition;
		internal static ref bool GetWafer_target_die_check_Rec(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_target_die_check_Rec;
		internal static ref bool GetWafer_check_die(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_check_die;
		internal static ref bool GetWafer_die_Rec_error_mode_Conflict(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_die_Rec_error_mode_Conflict;
		internal static ref bool GetDie_outline_recognition_mode(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Die_outline_recognition_mode;
		internal static ref bool GetDie_presence_recognition(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Die_presence_recognition;
		internal static ref bool GetDie_crack_detection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Die_crack_detection;
		internal static ref bool GetWafer_Die_surface_Judg_Insp(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_Die_surface_Judg_Insp;
		internal static ref bool GetPreform_motion_mode(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_motion_mode;
		internal static ref bool GetDispenser_motion(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Dispenser_motion;
		internal static ref bool GetPaste_remain_detection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Paste_remain_detection;
		internal static ref bool GetPreform_cleaning(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_cleaning;
		internal static ref bool GetPreform_paddle_recognition(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_paddle_recognition;
		internal static ref bool GetPreform_fail_mark_recognition(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_fail_mark_recognition;
		internal static ref bool GetPreform_Presence_inspection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_Presence_inspection;
		internal static ref bool GetPreform_area_inspection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_area_inspection;
		internal static ref bool GetPreform_form_inspection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_form_inspection;
		internal static ref bool GetReverse_frame_recognition(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Reverse_frame_recognition;
		internal static ref bool GetPickup_Die_BIN_select(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Pickup_Die_BIN_select;
		internal static ref bool GetBonding_pickup_mode(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_pickup_mode;
		internal static ref bool GetPre_heat(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Pre_heat;
		internal static ref bool GetBond_heat(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bond_heat;
		internal static ref bool GetAfter_heat(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_After_heat;
		internal static ref bool GetBonding_paddle_recognition(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_paddle_recognition;
		internal static ref bool GetBonding_inspection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_inspection;
		internal static ref bool GetBefore_bonding_inspection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Before_bonding_inspection;
		internal static ref bool GetBonding_Die_surface_Judg_Insp(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_Die_surface_Judg_Insp;
		internal static ref bool GetAlignment_stage_die_recognition(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Alignment_stage_die_recognition;
		internal static ref bool GetAlignment_stage_particle_inspection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Alignment_stage_particle_inspection;
		internal static ref bool GetAlignment_stage_Die_surface_inspection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Alignment_stage_Die_surface_inspection;
		internal static ref bool GetFrame_feed(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Frame_feed;
		internal static ref bool GetWafer_feed(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Wafer_feed;
		internal static ref bool GetPreform_motion(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_motion;
		internal static ref bool GetBonding_motion(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_motion;
		internal static ref bool GetUtility_check(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Utility_check;
		internal static ref bool GetDouble_frame_detection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Double_frame_detection;
		internal static ref bool GetPreform_stage_Vac_Det(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_stage_Vac_Det;
		internal static ref bool GetBonding_stage_Vac_Det(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_stage_Vac_Det;
		internal static ref bool GetALIGN_stage_Vac_Det(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_ALIGN_stage_Vac_Det;
		internal static ref bool GetDie_pickup_vacuum_detection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Die_pickup_vacuum_detection;
		internal static ref bool GetDie_Det_after_stage_place(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Die_Det_after_stage_place;
		internal static ref bool GetDie_Det_after_stage_pickup(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Die_Det_after_stage_pickup;
		internal static ref bool GetBonding_vacuum_detection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_vacuum_detection;
		internal static ref bool GetBonding_land_detection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Bonding_land_detection;
		internal static ref bool GetPickup_head_land_detection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Pickup_head_land_detection;
		internal static ref bool GetCollect_cleaning_mode(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Collect_cleaning_mode;
		internal static ref bool GetPreform_circle_form_inspection(this GVL_Recipe_BoolWrapper parent) => ref parent.ref_Preform_circle_form_inspection;
	}

}
