using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using TwinCAT.Ads;
using PLCManager.Demo.Enum;
using PLCManager.Demo.Struct;
using PLCManager.Demo.Wrapper;
using PlcCore.Beckhoff;
using PlcCore.Data;

namespace PLCManager.Demo.Root
{
	
	internal static class GetClass_db8b1549e65c40e299ff85714464e68b
	{
		internal static ref bool GetG_I_IMH_ZM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_ZM_PL;
		internal static ref bool GetG_I_IMH_ZM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_ZM_OL;
		internal static ref bool GetG_I_IMH_ZM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_ZM_NL;
		internal static ref bool GetG_I_IMH_YM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_YM_PL;
		internal static ref bool GetG_I_IMH_YM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_YM_OL;
		internal static ref bool GetG_I_IMH_YM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_YM_NL;
		internal static ref bool GetG_I_IMH_LDF_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_LDF_PL;
		internal static ref bool GetG_I_IMH_LDF_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_LDF_NL;
		internal static ref bool GetG_I_IMH_ZC_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_ZC_PL;
		internal static ref bool GetG_I_IMH_ZC_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_ZC_NL;
		internal static ref bool GetG_I_IMH_YC_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_YC_PL;
		internal static ref bool GetG_I_IMH_YC_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_YC_NL;
		internal static ref bool GetG_I_IMH_SPC_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_SPC_PL;
		internal static ref bool GetG_I_IMH_SPC_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_SPC_NL;
		internal static ref bool GetG_I_IMH_SAC_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_SAC_SR;
		internal static ref bool GetG_I_IMH_SDD_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_SDD_SR;
		internal static ref bool GetG_I_IMH_MPD_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_MPD_SR;
		internal static ref bool GetG_I_IMH_MFD_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_IMH_MFD_SR;
		internal static ref bool GetG_I_OMH_ZM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_ZM_PL;
		internal static ref bool GetG_I_OMH_ZM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_ZM_OL;
		internal static ref bool GetG_I_OMH_ZM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_ZM_NL;
		internal static ref bool GetG_I_OMH_YM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_YM_PL;
		internal static ref bool GetG_I_OMH_YM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_YM_OL;
		internal static ref bool GetG_I_OMH_YM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_YM_NL;
		internal static ref bool GetG_I_OMH_LDF_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_LDF_PL;
		internal static ref bool GetG_I_OMH_LDF_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_LDF_NL;
		internal static ref bool GetG_I_OMH_ZC_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_ZC_PL;
		internal static ref bool GetG_I_OMH_ZC_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_ZC_NL;
		internal static ref bool GetG_I_OMH_YC_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_YC_PL;
		internal static ref bool GetG_I_OMH_YC_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_YC_NL;
		internal static ref bool GetG_I_OMH_SDD_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_SDD_SR;
		internal static ref bool GetG_I_OMH_MPD_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_MPD_SR;
		internal static ref bool GetG_I_OMH_MFD_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_OMH_MFD_SR;
		internal static ref bool GetG_I_FIG_SFP_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FIG_SFP_SR;
		internal static ref bool GetG_I_FIG_SPD_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FIG_SPD_SR;
		internal static ref bool GetG_I_FIG_RVS_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FIG_RVS_SR;
		internal static ref bool GetG_I_FIG_IFO_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FIG_IFO_SR;
		internal static ref bool GetG_I_FIG_CM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FIG_CM_OL;
		internal static ref bool GetG_I_FIG_XM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FIG_XM_PL;
		internal static ref bool GetG_I_FIG_XM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FIG_XM_OL;
		internal static ref bool GetG_I_FIG_XM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FIG_XM_NL;
		internal static ref bool GetG_I_FCU_SIP_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_SIP_SR;
		internal static ref bool GetG_I_FCU_TRC_SR1(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_TRC_SR1;
		internal static ref bool GetG_I_FCU_TRC_SR2(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_TRC_SR2;
		internal static ref bool GetG_I_FCU_PRA_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_PRA_SR;
		internal static ref bool GetG_I_FCU_NRA_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_NRA_SR;
		internal static ref bool GetG_I_FCU_LXM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_LXM_PL;
		internal static ref bool GetG_I_FCU_LXM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_LXM_OL;
		internal static ref bool GetG_I_FCU_LXM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_LXM_NL;
		internal static ref bool GetG_I_FCU_CM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_CM_OL;
		internal static ref bool GetG_I_FCU_CDA_YM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_CDA_YM_OL;
		internal static ref bool GetG_I_FCU_CDA_ZM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_CDA_ZM_PL;
		internal static ref bool GetG_I_FCU_CDA_ZM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_CDA_ZM_NL;
		internal static ref bool GetG_I_FCU_PCM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_PCM_OL;
		internal static ref bool GetG_I_FCU_SZM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_SZM_PL;
		internal static ref bool GetG_I_FCU_SZM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_SZM_OL;
		internal static ref bool GetG_I_FCU_SZM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FCU_SZM_NL;
		internal static ref bool GetG_I_FBU_UTC_SR1(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_UTC_SR1;
		internal static ref bool GetG_I_FBU_UTC_SR2(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_UTC_SR2;
		internal static ref int GetG_AI_FCU_PHT(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_AI_FCU_PHT;
		internal static ref int GetG_AI_FCU_HCM(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_AI_FCU_HCM;
		internal static ref int GetG_AI_FCU_RDV(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_AI_FCU_RDV;
		internal static ref bool GetG_I_FBU_BCM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_BCM_OL;
		internal static ref bool GetG_I_FBU_BZ1M_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_BZ1M_PL;
		internal static ref bool GetG_I_FBU_BZ1M_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_BZ1M_OL;
		internal static ref bool GetG_I_FBU_BZ1M_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_BZ1M_NL;
		internal static ref bool GetG_I_FBU_BZ2M_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_BZ2M_PL;
		internal static ref bool GetG_I_FBU_BZ2M_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_BZ2M_OL;
		internal static ref bool GetG_I_FBU_BZ2M_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_BZ2M_NL;
		internal static ref bool GetG_I_FBU_LXM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_LXM_PL;
		internal static ref bool GetG_I_FBU_LXM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_LXM_OL;
		internal static ref bool GetG_I_FBU_LXM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_LXM_NL;
		internal static ref bool GetG_I_FBU_CM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_CM_OL;
		internal static ref bool GetG_I_FBU_V_XM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_V_XM_PL;
		internal static ref bool GetG_I_FBU_V_XM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_V_XM_OL;
		internal static ref bool GetG_I_FBU_V_XM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_V_XM_NL;
		internal static ref bool GetG_I_FBU_V_YM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_V_YM_PL;
		internal static ref bool GetG_I_FBU_V_YM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_V_YM_OL;
		internal static ref bool GetG_I_FBU_V_YM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_V_YM_NL;
		internal static ref bool GetG_I_FBU_AZM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_AZM_PL;
		internal static ref bool GetG_I_FBU_AZM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_AZM_OL;
		internal static ref bool GetG_I_FBU_AZM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_AZM_NL;
		internal static ref bool GetG_I_FBU_TWM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FBU_TWM_OL;
		internal static ref bool GetG_I_FOG_USS_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FOG_USS_PL;
		internal static ref bool GetG_I_FOG_LXM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FOG_LXM_PL;
		internal static ref bool GetG_I_FOG_LXM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FOG_LXM_OL;
		internal static ref int GetG_AI_FBU_HTR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_AI_FBU_HTR;
		internal static ref int GetG_AI1_FBU_NPA(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_AI1_FBU_NPA;
		internal static ref int GetG_AI2_FBU_NPA(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_AI2_FBU_NPA;
		internal static ref int GetG_AI3_FBU_NPA(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_AI3_FBU_NPA;
		internal static ref bool GetG_I_FOG_LXM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FOG_LXM_NL;
		internal static ref bool GetG_I_FOG_ZM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_FOG_ZM_OL;
		internal static ref bool GetG_I_WLU_FRI_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_FRI_SR;
		internal static ref bool GetG_I_WLU_RRI_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_RRI_SR;
		internal static ref bool GetG_I_WLU_FRO_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_FRO_SR;
		internal static ref bool GetG_I_WLU_RRO_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_RRO_SR;
		internal static ref bool GetG_I_WLU_WTS_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_WTS_SR;
		internal static ref bool GetG_I_WLU_WRS_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_WRS_SR;
		internal static ref bool GetG_I_WLU_WPD_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_WPD_SR;
		internal static ref bool GetG_I_WLU_WJS_SR(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_WJS_SR;
		internal static ref bool GetG_I_WLU_CAP_SR1(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_CAP_SR1;
		internal static ref bool GetG_I_WLU_CAP_SR2(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_CAP_SR2;
		internal static ref bool GetG_I_WLU_ZM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_ZM_PL;
		internal static ref bool GetG_I_WLU_ZM_WL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_ZM_WL;
		internal static ref bool GetG_I_WLU_ZM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_ZM_OL;
		internal static ref bool GetG_I_WLU_ZM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_ZM_NL;
		internal static ref bool GetG_I_WLU_XM_PL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_XM_PL;
		internal static ref bool GetG_I_WLU_XM_OL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_XM_OL;
		internal static ref bool GetG_I_WLU_XM_NL(this GVL_Sensor_UsedWrapper parent) => ref parent.ref_G_I_WLU_XM_NL;
	}

}
