using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using TwinCAT.Ads;
using PLCManager.Demo.Enum;
using PLCManager.Demo.Struct;
using PLCManager.Demo.Wrapper;
using PlcCore.Beckhoff;
using PlcCore.Data;

namespace PLCManager.Demo.Root
{
	
	internal static class GetClass_0bd6e564738842f08fbf004591a05efd
	{
		internal static ref float GetPreform_stage_down_delay(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Preform_stage_down_delay;
		internal static ref float GetDelay_after_preform_stage_up(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Delay_after_preform_stage_up;
		internal static ref float GetPreform_stage_down_pos(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Preform_stage_down_pos;
		internal static ref float GetPreform_stage_upper_pos(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Preform_stage_upper_pos;
		internal static ref float GetPreform_stage_going_up_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Preform_stage_going_up_speed;
		internal static ref float GetPS_vacuum_release_time(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_PS_vacuum_release_time;
		internal static ref float GetPreform_clamp_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Preform_clamp_speed_Fast;
		internal static ref float GetPreform_clamp_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Preform_clamp_speed_Slow;
		internal static ref float GetBonding_stage_down_delay(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Bonding_stage_down_delay;
		internal static ref float GetDelay_after_bonding_stage_up(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Delay_after_bonding_stage_up;
		internal static ref float GetBonding_stage_down_pos(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Bonding_stage_down_pos;
		internal static ref float GetBonding_stage_upper_pos(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Bonding_stage_upper_pos;
		internal static ref float GetBonding_stage_going_up_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Bonding_stage_going_up_speed;
		internal static ref float GetBonding_stage_pos_while_stop(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Bonding_stage_pos_while_stop;
		internal static ref float GetBS_vacuum_release_time(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_BS_vacuum_release_time;
		internal static ref float GetBS_Vac_Det_retry_count(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_BS_Vac_Det_retry_count;
		internal static ref float GetBS_Vac_Det_retry_time(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_BS_Vac_Det_retry_time;
		internal static ref bool GetRe_clamp_at_Vac_Det_retry(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Re_clamp_at_Vac_Det_retry;
		internal static ref bool GetAction_after_FRM_pullout_error(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Action_after_FRM_pullout_error;
		internal static ref bool GetFrame_pusher_usage(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_pusher_usage;
		internal static ref bool GetFrame_cleaning(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_cleaning;
		internal static ref float GetBonding_clamp_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Bonding_clamp_speed_Fast;
		internal static ref float GetBonding_clamp_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Bonding_clamp_speed_Slow;
		internal static ref float GetFrame_head_detection_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_head_detection_speed;
		internal static ref float GetFrame_grip_position(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_grip_position;
		internal static ref float GetGripper_stroke_one_side_in_MGZ(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Gripper_stroke_one_side_in_MGZ;
		internal static ref float GetFrame_Det_sens_offset_Rear(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_Det_sens_offset_Rear;
		internal static ref float GetLoader_feeder_transfer_timer(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Loader_feeder_transfer_timer;
		internal static ref float GetFrame_pullout_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_pullout_speed;
		internal static ref float GetFrame_pullout_pitch(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_pullout_pitch;
		internal static ref float GetFrame_pullout_retry_count(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_pullout_retry_count;
		internal static ref float GetGrip_pos_offset_at_retry(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Grip_pos_offset_at_retry;
		internal static ref float GetFrame_return_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_return_speed;
		internal static ref float GetFIG_feeder_transfer_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FIG_feeder_transfer_speed;
		internal static ref float GetFIG_feeder_return_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FIG_feeder_return_speed_Fast;
		internal static ref float GetFIG_feeder_return_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FIG_feeder_return_speed_Slow;
		internal static ref float GetFIG_grip_motion_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FIG_grip_motion_Fast;
		internal static ref float GetFIG_grip_motion_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FIG_grip_motion_Slow;
		internal static ref float GetFIG_frame_head_detect_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FIG_frame_head_detect_speed;
		internal static ref float GetFIG_grip_pos(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FIG_grip_pos;
		internal static ref float GetFIG_Gripper_Stroke(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FIG_Gripper_Stroke;
		internal static ref float GetFIG_Frame_Detect_Sensor_Offset(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FIG_Frame_Detect_Sensor_Offset;
		internal static ref float GetFIG_Loader_feeder_Transfer_Timer(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FIG_Loader_feeder_Transfer_Timer;
		internal static ref float GetReverse_Frame_DetSpeed1(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Reverse_Frame_DetSpeed1;
		internal static ref float GetReverse_Frame_DetSpeed2(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Reverse_Frame_DetSpeed2;
		internal static ref float GetFCU_Main_feeder1_transfer_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FCU_Main_feeder1_transfer_speed;
		internal static ref float GetFCU_Main_feeder1_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FCU_Main_feeder1_speed_Fast;
		internal static ref float GetFCU_Main_feeder1_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FCU_Main_feeder1_speed_Slow;
		internal static ref float GetFCU_MF_1_grip_motion_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FCU_MF_1_grip_motion_Fast;
		internal static ref float GetFCU_MF_1_grip_motion_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FCU_MF_1_grip_motion_Slow;
		internal static ref float GetFCU_P_frame_clamp_transfer_timer(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FCU_P_frame_clamp_transfer_timer;
		internal static ref float GetFBU_Main_feeder2_transfer_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FBU_Main_feeder2_transfer_speed;
		internal static ref float GetFBU_Main_feeder2_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FBU_Main_feeder2_speed_Fast;
		internal static ref float GetFBU_Main_feeder2_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FBU_Main_feeder2_speed_Slow;
		internal static ref float GetFBU_MF_2_grip_motion_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FBU_MF_2_grip_motion_Fast;
		internal static ref float GetFBU_MF_2_grip_motion_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FBU_MF_2_grip_motion_Slow;
		internal static ref float GetFBU_Unload_feeder_transfer_timer(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FBU_Unload_feeder_transfer_timer;
		internal static ref float GetFBU_B_frame_clamp_transfer_timer(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_FBU_B_frame_clamp_transfer_timer;
		internal static ref float GetUL_F_transfer_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_UL_F_transfer_speed;
		internal static ref float GetUnload_feeder_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Unload_feeder_speed_Fast;
		internal static ref float GetUnload_feeder_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Unload_feeder_speed_Slow;
		internal static ref float GetUL_F_grip_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_UL_F_grip_speed_Fast;
		internal static ref float GetUL_F_grip_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_UL_F_grip_speed_Slow;
		internal static ref float GetLAF_transfer_timer(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_LAF_transfer_timer;
		internal static ref float GetFrame_push_out_pos(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_push_out_pos;
		internal static ref float GetFrame_unload_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_unload_speed;
		internal static ref float GetFrame_overload_return_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_overload_return_speed;
		internal static ref float GetFrame_unload_pitch(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_unload_pitch;
		internal static ref float GetFrame_unload_speed_change_pos(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_unload_speed_change_pos;
		internal static ref float GetStrip_insert_speed1(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Strip_insert_speed1;
		internal static ref float GetStrip_insert_speed2(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Strip_insert_speed2;
		internal static ref float GetFrame_unload_timer(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_unload_timer;
		internal static ref bool GetFrame_unload_jam_detection(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Frame_unload_jam_detection;
		internal static ref bool GetIMH_Magazine_flow_direction(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_Magazine_flow_direction;
		internal static ref short GetG_Clean_Row_Num(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_Clean_Row_Num;
		internal static ref float GetCure_I_F_Time_out1(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Cure_I_F_Time_out1;
		internal static ref float GetCure_I_F_Time_out2(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_Cure_I_F_Time_out2;
		internal static ref float GetG_FIG_XM_TO_Sensor_Pos(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_FIG_XM_TO_Sensor_Pos;
		internal static ref float GetG_FIG_XM_TO_Preform_Pos(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_FIG_XM_TO_Preform_Pos;
		internal static ref float GetG_FIG_CM_TO_Preform_Pos(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_FIG_CM_TO_Preform_Pos;
		internal static ref short GetG_FIG_TO_FCU_Row_Num(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_FIG_TO_FCU_Row_Num;
		internal static ref short GetG_FCU_Row_Num(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_FCU_Row_Num;
		internal static ref short GetG_FCU_TO_FBU_Row_Num(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_FCU_TO_FBU_Row_Num;
		internal static ref short GetG_FBU_Row_Num(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_FBU_Row_Num;
		internal static ref short GetG_Clean_Base_MaxRow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_Clean_Base_MaxRow;
		internal static ref short GetG_Clean_MoveBase_Num(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_Clean_MoveBase_Num;
		internal static ref short GetG_Bonding_MaxRow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_Bonding_MaxRow;
		internal static ref short GetG_Bonded_Num(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_Bonded_Num;
		internal static ref float GetIMH_ZM_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_ZM_speed_Fast;
		internal static ref float GetIMH_ZM_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_ZM_speed_Slow;
		internal static ref float GetIMH_YM_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_YM_speed_Fast;
		internal static ref float GetIMH_YM_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_YM_speed_Slow;
		internal static ref float GetIMH_YC_response_time(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_YC_response_time;
		internal static ref float GetIMH_ZC_response_time(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_ZC_response_time;
		internal static ref bool GetIMH_Magazine_transfer_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_Magazine_transfer_speed;
		internal static ref bool GetIMH_MGZ_Load_Flow_DIR(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_MGZ_Load_Flow_DIR;
		internal static ref bool GetIMH_MGZ_Transfer_Speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_MGZ_Transfer_Speed;
		internal static ref bool GetOMH_Magazine_flow_direction(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_Magazine_flow_direction;
		internal static ref float GetIMH_Frame_Pusher_Push_Speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_Frame_Pusher_Push_Speed;
		internal static ref float GetIMH_Frame_Pusher_Return_Speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_Frame_Pusher_Return_Speed;
		internal static ref float GetIMH_Side_Clamp_Response_Time(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_IMH_Side_Clamp_Response_Time;
		internal static ref float GetOMH_ZM_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_ZM_speed_Fast;
		internal static ref float GetOMH_ZM_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_ZM_speed_Slow;
		internal static ref float GetOMH_YM_speed_Fast(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_YM_speed_Fast;
		internal static ref float GetOMH_YM_speed_Slow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_YM_speed_Slow;
		internal static ref float GetOMH_ZC_response_time(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_ZC_response_time;
		internal static ref float GetOMH_YC_response_time(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_YC_response_time;
		internal static ref bool GetOMH_Magazine_transfer_speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_Magazine_transfer_speed;
		internal static ref bool GetOMH_MGZ_Load_Flow_DIR(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_MGZ_Load_Flow_DIR;
		internal static ref bool GetOMH_MGZ_Transfer_Speed(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_MGZ_Transfer_Speed;
		internal static ref float GetOMH_Side_Clamp_Response_Time(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_OMH_Side_Clamp_Response_Time;
		internal static ref short GetG_BasePitch_EveryRow(this GVL_Recipe_TransferSettingWrapper parent) => ref parent.ref_G_BasePitch_EveryRow;
	}

}
