using System;
using System.Runtime.InteropServices;

namespace PLCManager.Demo.Enum
{
	/// <summary>
	/// Name from PLC:Tc2_MC2.E_EncoderReferenceMode
	/// PLCNamespace from PLC: 5.113.195.149.1.1:851
	/// Size: 4
	/// Comment from PLC: 
	/// <summary>
	public enum Tc2_MC2_E_EncoderReferenceMode : uint
	{
		ENCODERREFERENCEMODE_DEFAULT = 0,
		ENCODERREFERENCEMODE_PLCCAM = 1,
		ENCODERREFERENCEMODE_HARDWARESYNC = 2,
		ENCODERREFERENCEMODE_HARDWARELATCHPOS = 3,
		ENCODERREFERENCEMODE_HARDWARELATCHNEG = 4,
		ENCODERREFERENCEMODE_SOFTWARESYNC = 5,
		ENCODERREFERENCEMODE_SOFTDRIVELATCHPOS = 6,
		ENCODERREFERENCEMODE_SOFTDRIVELATCHNEG = 7,
		ENCODERREFERENCEMODE_APPLICATION = 20,

	}
}
