using System;
using System.Runtime.InteropServices;

namespace PLCManager.Demo.Enum
{
	/// <summary>
	/// Name from PLC:Tc2_MC2._E_TcNC_StartPosType
	/// PLCNamespace from PLC: 5.113.195.149.1.1:851
	/// Size: 2
	/// Comment from PLC: 
	/// <summary>
	public enum Tc2_MC2__E_TcNC_StartPosType : ushort
	{
		TCNC_START_ABSOLUTE = 1,
		TCNC_START_RELATIVE = 2,
		TCNC_START_ENDLESS_PLUS = 3,
		TCNC_START_ENDLESS_MINUS = 4,
		TCNC_START_MODULO = 5,
		TCNC_START_ADDITIVE = 6,
		TCNC_START_MODULO_SHORT = 261,
		TCNC_START_MODULO_PLUS = 517,
		TCNC_START_MODULO_MINUS = 773,
		TCNC_START_MODULO_CURRENT = 1029,
		TCNC_START_ABS_INTERNAL = 9,
		TCNC_START_ENDLESSPLUS_SLOWMANUAL = 272,
		TCNC_START_ENDLESSMINUS_SLOWMANUAL = 273,
		TCNC_START_ENDLESSPLUS_FASTMANUAL = 528,
		TCNC_START_ENDLESSMINUS_FASTMANUAL = 529,
		TCNC_START_STOPANDLOCK = 4096,
		TCNC_START_HALT = 8192,
		TCNC_START_TORQUE_ABORT = 12288,
		TCNC_START_TORQUE_ABSOLUTE = 12289,
		TCNC_START_TORQUE_RELATIVE = 12290,

	}
}
